CREATE DATABASE IF NOT EXISTS `user`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS `event`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'userpass';
GRANT ALL PRIVILEGES ON `user`.* TO 'user'@'%';

CREATE USER IF NOT EXISTS 'event'@'%' IDENTIFIED BY 'eventpass';
GRANT ALL PRIVILEGES ON `event`.* TO 'event'@'%';

CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED BY 'replpass';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl'@'%';

CREATE USER IF NOT EXISTS 'mysql-exporter'@'%' IDENTIFIED BY 'mysql-exporterpass';
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'mysql-exporter'@'%';

FLUSH PRIVILEGES;